# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cf7003a20b690bc67f675d24309330ce832484f9bad091ef948798e93173d4a2facb2637d3a8696b46b7a08e0cc8f285d2faddb6201d214e7739f986237a87b

test:
  secret_key_base: 0985f01a75aa0ad42e21351c7faaeb83b91940a767a6e0b2d24d1cbaaddebc43c2667cfe0233e9b20fa7a4acc9da0247bad2a2a1f94169efb6f008509b9f5fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
